// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Result = require("rescript/lib/js/belt_Result.js");
var SchemaDriven = require("../src/SchemaDriven.bs.js");
var SchemaDrivenRescriptStructPlugin = require("../src/SchemaDrivenRescriptStructPlugin.bs.js");

var _genDir = (require("path").resolve(module.path, "..", "..", "..", "_generated"));

var eng = Belt_Result.getExn(SchemaDriven.defEngine(_genDir, [SchemaDrivenRescriptStructPlugin.plugin], /* RemoveAllFilesFromDir */0));

var testOptionInt = Belt_Result.getExn(SchemaDriven.optionNull("TestOptionInt", SchemaDriven.$$int, eng));

var testPerson = Belt_Result.getExn(SchemaDriven.record("Test-Person", [
          /* ObjectProp */{
            _0: "id",
            _1: SchemaDriven.$$int
          },
          /* ObjectProp */{
            _0: "ages",
            _1: testOptionInt
          },
          /* ObjectProp */{
            _0: "name",
            _1: SchemaDriven.string
          }
        ], eng));

exports._genDir = _genDir;
exports.eng = eng;
exports.testOptionInt = testOptionInt;
exports.testPerson = testPerson;
/* _genDir Not a pure module */
