// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");
var SchemaDrivenNamesCorrector = require("../src/SchemaDrivenNamesCorrector.bs.js");

Mocha$RescriptMocha.describe("SchemaDrivenNamesCorrectorTest")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.describe("test modifyVariableName")(undefined, undefined, undefined, (function (param) {
                Mocha$RescriptMocha.it("test 1")(undefined, undefined, undefined, (function (param) {
                        var result = SchemaDrivenNamesCorrector.modifyVariableName("Mom-givesMe*_a(Soap )");
                        Assert$RescriptMocha.equal(undefined, result, "momgivesMe_aSoap");
                      }));
                Mocha$RescriptMocha.it("test 2")(undefined, undefined, undefined, (function (param) {
                        var result = SchemaDrivenNamesCorrector.modifyVariableName("wellVarName");
                        Assert$RescriptMocha.equal(undefined, result, "wellVarName");
                      }));
              }));
        Mocha$RescriptMocha.describe("test modifyVariantName")(undefined, undefined, undefined, (function (param) {
                Mocha$RescriptMocha.it("test 1")(undefined, undefined, undefined, (function (param) {
                        var result = SchemaDrivenNamesCorrector.modifyVariantName("mom-givesMe*_a(Soap )");
                        Assert$RescriptMocha.equal(undefined, result, "MomgivesMe_aSoap");
                      }));
                Mocha$RescriptMocha.it("test 2")(undefined, undefined, undefined, (function (param) {
                        var result = SchemaDrivenNamesCorrector.modifyVariantName("WellVarName_");
                        Assert$RescriptMocha.equal(undefined, result, "WellVarName_");
                      }));
              }));
        Mocha$RescriptMocha.describe("test modifyModuleName")(undefined, undefined, undefined, (function (param) {
                Mocha$RescriptMocha.it("test 1")(undefined, undefined, undefined, (function (param) {
                        var result = SchemaDrivenNamesCorrector.modifyModuleName("mom-givesMe*_a(Soap )");
                        Assert$RescriptMocha.equal(undefined, result, "MomgivesMe_aSoap");
                      }));
                Mocha$RescriptMocha.it("test 2")(undefined, undefined, undefined, (function (param) {
                        var result = SchemaDrivenNamesCorrector.modifyModuleName("WellVarName_");
                        Assert$RescriptMocha.equal(undefined, result, "WellVarName_");
                      }));
              }));
      }));

/*  Not a pure module */
