// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenModule = require("../src/SchemaDrivenModule.bs.js");
var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");

Mocha$RescriptMocha.describe("SchemaDrivenModuleTest")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.it("test basics")(undefined, undefined, undefined, (function (param) {
                var given = "SomeModuleName";
                var result = SchemaDrivenModule.moduleName(SchemaDrivenModule.def(given));
                Assert$RescriptMocha.equal(undefined, result, given);
              }));
      }));

/*  Not a pure module */
