// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Result = require("rescript/lib/js/belt_Result.js");
var SchemaDrivenInt = require("../src/SchemaDrivenInt.bs.js");
var S$RescriptStruct = require("rescript-struct/lib/js/src/S.bs.js");
var SchemaDrivenBool = require("../src/SchemaDrivenBool.bs.js");
var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");

Mocha$RescriptMocha.describe("SchemaDrivenIntTest")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.it("test assertion")(undefined, undefined, undefined, (function (param) {
                var result = S$RescriptStruct.parseWith(22, SchemaDrivenInt.struct);
                Assert$RescriptMocha.deep_equal(undefined, result, {
                      TAG: /* Ok */0,
                      _0: 22
                    });
              }));
        Mocha$RescriptMocha.it("test invalid")(undefined, undefined, undefined, (function (param) {
                var result = S$RescriptStruct.parseWith("", SchemaDrivenBool.struct);
                Assert$RescriptMocha.ok(Belt_Result.isError(result));
              }));
        Mocha$RescriptMocha.it("test serialization")(undefined, undefined, undefined, (function (param) {
                var result = Belt_Result.flatMap(S$RescriptStruct.serializeToJsonWith(-11, undefined, SchemaDrivenInt.struct), (function (s) {
                        return S$RescriptStruct.parseJsonWith(s, SchemaDrivenInt.struct);
                      }));
                Assert$RescriptMocha.deep_equal(undefined, result, {
                      TAG: /* Ok */0,
                      _0: -11
                    });
              }));
      }));

/*  Not a pure module */
