// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var S$RescriptStruct = require("rescript-struct/lib/js/src/S.bs.js");
var SchemaDrivenBool = require("../src/SchemaDrivenBool.bs.js");

var struct = S$RescriptStruct.$$null(SchemaDrivenBool.struct);

exports.struct = struct;
/* struct Not a pure module */
