// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenModule = require("../src/SchemaDrivenModule.bs.js");

var testOptionInt = SchemaDrivenModule.def("TestOptionInt");

var testOptionStr = SchemaDrivenModule.def("TestOptionStr");

var testPerson = SchemaDrivenModule.def("TestPerson");

var testProfile = SchemaDrivenModule.def("TestProfile");

var testVariantObject = SchemaDrivenModule.def("TestVariantObject");

var testVariantContainer = SchemaDrivenModule.def("TestVariantContainer");

var testVariantLiteral = SchemaDrivenModule.def("TestVariantLiteral");

var testTupleN = SchemaDrivenModule.def("TestTupleN");

var testArray = SchemaDrivenModule.def("TestArray");

var testList = SchemaDrivenModule.def("TestList");

var testDict = SchemaDrivenModule.def("TestDict");

var crazyTaggedVariant = SchemaDrivenModule.def("CrazyTaggedVariant");

exports.testOptionInt = testOptionInt;
exports.testOptionStr = testOptionStr;
exports.testPerson = testPerson;
exports.testProfile = testProfile;
exports.testVariantObject = testVariantObject;
exports.testVariantContainer = testVariantContainer;
exports.testVariantLiteral = testVariantLiteral;
exports.testTupleN = testTupleN;
exports.testArray = testArray;
exports.testList = testList;
exports.testDict = testDict;
exports.crazyTaggedVariant = crazyTaggedVariant;
/* testOptionInt Not a pure module */
