// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TestOptionStr = require("./TestOptionStr.bs.js");
var SchemaDrivenInt = require("../src/SchemaDrivenInt.bs.js");
var S$RescriptStruct = require("rescript-struct/lib/js/src/S.bs.js");
var SchemaDrivenBool = require("../src/SchemaDrivenBool.bs.js");
var SchemaDrivenRescriptStructPlugin = require("../src/SchemaDrivenRescriptStructPlugin.bs.js");

var struct = S$RescriptStruct.$$Object.strip(S$RescriptStruct.object(function (o) {
          return [
                  S$RescriptStruct.field(o, "t_0", SchemaDrivenInt.struct),
                  S$RescriptStruct.field(o, "t_1", TestOptionStr.struct),
                  S$RescriptStruct.field(o, "t_2", SchemaDrivenBool.struct)
                ];
        }));

function parse(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.parseWith(x, struct));
}

function parseAny(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.parseAnyWith(x, struct));
}

function parseJson(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.parseJsonWith(x, struct));
}

function parseAsync(x) {
  return SchemaDrivenRescriptStructPlugin.thenStructErrToExn(S$RescriptStruct.parseAsyncWith(x, struct));
}

function serialize(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.serializeWith(x, struct));
}

function serializeToUnknown(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.serializeToUnknownWith(x, struct));
}

function serializeToJson(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.serializeToJsonWith(x, undefined, struct));
}

exports.struct = struct;
exports.parse = parse;
exports.parseAny = parseAny;
exports.parseJson = parseJson;
exports.parseAsync = parseAsync;
exports.serialize = serialize;
exports.serializeToUnknown = serializeToUnknown;
exports.serializeToJson = serializeToJson;
/* struct Not a pure module */
