// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var S$RescriptStruct = require("rescript-struct/lib/js/src/S.bs.js");
var SchemaDrivenRescriptStructPlugin = require("../src/SchemaDrivenRescriptStructPlugin.bs.js");

var struct = S$RescriptStruct.union([
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "Banana"
          }, /* Banana */0),
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "Orange"
          }, /* Orange */1),
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "Apple"
          }, /* Apple */2)
    ]);

var allVariants = [
  "Banana",
  "Orange",
  "Apple"
];

function parse(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.parseWith(x, struct));
}

function parseAny(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.parseAnyWith(x, struct));
}

function parseJson(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.parseJsonWith(x, struct));
}

function parseAsync(x) {
  return SchemaDrivenRescriptStructPlugin.thenStructErrToExn(S$RescriptStruct.parseAsyncWith(x, struct));
}

function serialize(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.serializeWith(x, struct));
}

function serializeToUnknown(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.serializeToUnknownWith(x, struct));
}

function serializeToJson(x) {
  return SchemaDrivenRescriptStructPlugin.structErrToExn(S$RescriptStruct.serializeToJsonWith(x, undefined, struct));
}

exports.allVariants = allVariants;
exports.struct = struct;
exports.parse = parse;
exports.parseAny = parseAny;
exports.parseJson = parseJson;
exports.parseAsync = parseAsync;
exports.serialize = serialize;
exports.serializeToUnknown = serializeToUnknown;
exports.serializeToJson = serializeToJson;
/* struct Not a pure module */
