open SchemaDrivenModule

let testOptionInt: schemaDrivenModule

let testOptionStr: schemaDrivenModule

let testPerson: schemaDrivenModule

let testProfile: schemaDrivenModule

let testVariantObject: schemaDrivenModule

let testVariantContainer: schemaDrivenModule

let testVariantLiteral: schemaDrivenModule

let testTupleN: schemaDrivenModule

let testArray: schemaDrivenModule

let testList: schemaDrivenModule

let testDict: schemaDrivenModule

let crazyTaggedVariant: schemaDrivenModule