// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenEngine = require("./SchemaDrivenEngine.bs.js");
var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");
var SchemaDrivenObject = require("./SchemaDrivenObject.bs.js");
var SchemaDrivenRecord = require("./SchemaDrivenRecord.bs.js");
var SchemaDrivenTupleN = require("./SchemaDrivenTupleN.bs.js");
var SchemaDrivenOptionNull = require("./SchemaDrivenOptionNull.bs.js");
var SchemaDrivenTupleObject = require("./SchemaDrivenTupleObject.bs.js");
var SchemaDrivenVariantObject = require("./SchemaDrivenVariantObject.bs.js");
var SchemaDrivenVariantContainer = require("./SchemaDrivenVariantContainer.bs.js");

var $$int = SchemaDrivenModule.def("SchemaDrivenInt");

var $$float = SchemaDrivenModule.def("SchemaDrivenFloat");

var string = SchemaDrivenModule.def("SchemaDrivenString");

var bool = SchemaDrivenModule.def("SchemaDrivenBool");

function optionNull(moduleName, t, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenOptionNull.makeResultCode(moduleName, t));
}

function record(moduleName, props, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenRecord.makeResultCode(moduleName, props));
}

function object(moduleName, props, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenObject.makeResultCode(moduleName, props));
}

function tupleN(moduleName, params, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenTupleN.makeResultCode(moduleName, params));
}

function tupleObject(moduleName, types, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenTupleObject.makeResultCode(moduleName, types));
}

function variantObject(moduleName, variants, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenVariantObject.makeResultCode(moduleName, variants));
}

function variantContainer(moduleName, variants, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenVariantContainer.makeResultCode(moduleName, variants));
}

var defEngine = SchemaDrivenEngine.def;

exports.defEngine = defEngine;
exports.$$int = $$int;
exports.$$float = $$float;
exports.string = string;
exports.bool = bool;
exports.optionNull = optionNull;
exports.record = record;
exports.object = object;
exports.tupleN = tupleN;
exports.tupleObject = tupleObject;
exports.variantObject = variantObject;
exports.variantContainer = variantContainer;
/* int Not a pure module */
