// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function make(moduleName, t, struct) {
  return {
          moduleName: moduleName,
          t: t,
          struct: struct,
          moduleTypes: ["SchemaDrivenModule"],
          funcDeclars: []
        };
}

function addModuleType(resultCodeDeclar, moduleType) {
  return {
          moduleName: resultCodeDeclar.moduleName,
          t: resultCodeDeclar.t,
          struct: resultCodeDeclar.struct,
          moduleTypes: Belt_Array.concat(resultCodeDeclar.moduleTypes, [moduleType]),
          funcDeclars: resultCodeDeclar.funcDeclars
        };
}

function addFuncs(resultCodeDeclar, funcs) {
  return {
          moduleName: resultCodeDeclar.moduleName,
          t: resultCodeDeclar.t,
          struct: resultCodeDeclar.struct,
          moduleTypes: resultCodeDeclar.moduleTypes,
          funcDeclars: Belt_Array.reduce(funcs, resultCodeDeclar.funcDeclars, (function (acc, f) {
                  if (acc.includes(f)) {
                    return acc;
                  } else {
                    return Belt_Array.concat(acc, [f]);
                  }
                }))
        };
}

function printModuleBody(resultCodeDeclar) {
  return Belt_Array.concat([
                "type t = " + resultCodeDeclar.t,
                "let struct: S.t<" + resultCodeDeclar.t + "> = " + resultCodeDeclar.struct
              ], resultCodeDeclar.funcDeclars).join("\n\n");
}

exports.make = make;
exports.addModuleType = addModuleType;
exports.addFuncs = addFuncs;
exports.printModuleBody = printModuleBody;
/* No side effect */
