// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");

function just(t) {
  switch (t) {
    case /* Int */0 :
        return SchemaDrivenModule.def("SchemaDrivenInt");
    case /* Float */1 :
        return SchemaDrivenModule.def("SchemaDrivenFloat");
    case /* String */2 :
        return SchemaDrivenModule.def("SchemaDrivenString");
    case /* Bool */3 :
        return SchemaDrivenModule.def("SchemaDrivenBool");
    case /* Unit */4 :
        return SchemaDrivenModule.def("SchemaDrivenUnit");
    
  }
}

exports.just = just;
/* No side effect */
