// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResultExn = require("rescript-result-exn/lib/js/src/ResultExn.bs.js");

function removeOnMatch(unexpectedFilesStrategy) {
  return unexpectedFilesStrategy === 1;
}

function cleanDirectory(path) {
  var clean = (function (directory) {
    const fs = require("fs");
    const path = require("path");
    const files = fs.readdirSync(directory);
    for (const file of files) {
      fs.unlinkSync(path.join(directory, file));
    }
  });
  return ResultExn.tryExec(function (param) {
              clean(path);
            });
}

function writeFileSync(file, data, removeOnMatch) {
  var f = (function (file, data, removeOnMatch) {
    let fs = require("fs");
    if(fs.existsSync(file)) {
      if(removeOnMatch) {
        fs.unlinkSync(file);
      } else {
        throw new Error("File " + file + " exists yet");
      }
    }
    fs.writeFileSync(file, data);
  });
  return ResultExn.tryExec(function (param) {
              f(file, data, removeOnMatch);
            });
}

exports.removeOnMatch = removeOnMatch;
exports.cleanDirectory = cleanDirectory;
exports.writeFileSync = writeFileSync;
/* No side effect */
