// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var SchemaDrivenResultCode = require("./SchemaDrivenResultCode.bs.js");
var SchemaDrivenNamesCorrector = require("./SchemaDrivenNamesCorrector.bs.js");

function printStruct(variants) {
  var variantRows = Belt_Array.map(variants, (function (v) {
          var v$p = SchemaDrivenNamesCorrector.modifyVariantName(v);
          return "  S.literalVariant(String(\"" + v$p + "\"), " + v$p + ")";
        }));
  return "S.union([\n" + variantRows.join(",\n") + "\n])";
}

function printType(variants) {
  var variantRows = Belt_Array.map(variants, (function (v) {
          return "  | " + SchemaDrivenNamesCorrector.modifyVariantName(v);
        }));
  return "\n" + variantRows.join("\n");
}

function allVariantsFunc(variants) {
  return "let allVariants = " + Belt_Option.getExn(JSON.stringify(variants));
}

function makeResultCode(moduleName, variants) {
  return SchemaDrivenResultCode.addModuleType(SchemaDrivenResultCode.addFuncs(SchemaDrivenResultCode.make(moduleName, printType(variants), printStruct(variants)), [allVariantsFunc(variants)]), "SchemaDrivenModule.SchemaDrivenVariantModule");
}

exports.printStruct = printStruct;
exports.printType = printType;
exports.makeResultCode = makeResultCode;
/* No side effect */
