// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var def = (function (moduleName) {
  return {
    module: moduleName
  };
});

var moduleName = (function (typeRef) {
  return typeRef.module;
});

exports.def = def;
exports.moduleName = moduleName;
/* No side effect */
