// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenEngine = require("./SchemaDrivenEngine.bs.js");
var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");
var SchemaDrivenResultCode = require("./SchemaDrivenResultCode.bs.js");

function printStruct(m) {
  return "S.null(" + SchemaDrivenModule.moduleName(m) + ".struct)";
}

function printType(m) {
  return "option<" + SchemaDrivenModule.moduleName(m) + ".t>";
}

function def(moduleName, t, engine) {
  var resultCode = SchemaDrivenResultCode.make(moduleName, printType(t), printStruct(t));
  return SchemaDrivenEngine.printModule(engine, moduleName, resultCode);
}

exports.printStruct = printStruct;
exports.printType = printType;
exports.def = def;
/* No side effect */
