// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenEngine = require("./SchemaDrivenEngine.bs.js");
var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");

function printStruct(m) {
  return "S.option(" + SchemaDrivenModule.moduleName(m) + ".struct)";
}

function printType(m) {
  return "option<" + SchemaDrivenModule.moduleName(m) + ".t>";
}

function def(moduleName, t, engine) {
  var structCode = printStruct(t);
  var typeCode = printType(t);
  var code = [
      "type t = " + typeCode + "",
      "let struct: S.t<" + typeCode + "> = " + structCode + ""
    ].join("\n\n");
  return SchemaDrivenEngine.printModule(engine, moduleName, code);
}

exports.printStruct = printStruct;
exports.printType = printType;
exports.def = def;
/* No side effect */
