// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenEngine = require("./SchemaDrivenEngine.bs.js");
var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");
var SchemaDrivenOptionNull = require("./SchemaDrivenOptionNull.bs.js");

var $$int = SchemaDrivenModule.def("SchemaDrivenInt");

var $$float = SchemaDrivenModule.def("SchemaDrivenFloat");

var string = SchemaDrivenModule.def("SchemaDrivenString");

var bool = SchemaDrivenModule.def("SchemaDrivenBool");

function optionNull(moduleName, t, engine) {
  return SchemaDrivenEngine.printModule(engine, moduleName, SchemaDrivenOptionNull.makeResultCode(moduleName, t));
}

var defEngine = SchemaDrivenEngine.def;

exports.defEngine = defEngine;
exports.$$int = $$int;
exports.$$float = $$float;
exports.string = string;
exports.bool = bool;
exports.optionNull = optionNull;
/* int Not a pure module */
