// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");
var SchemaDrivenResultCode = require("./SchemaDrivenResultCode.bs.js");

function printStruct(params) {
  var paramRows = Belt_Array.map(params, (function (p) {
          return "  " + SchemaDrivenModule.moduleName(p) + ".struct";
        }));
  return "S.Tuple.factory(. \n" + paramRows.join(",\n") + "\n)";
}

function printType(params) {
  var paramRows = Belt_Array.map(params, (function (p) {
          return "  " + SchemaDrivenModule.moduleName(p) + ".t";
        }));
  return "(\n" + paramRows.join(",\n") + "\n)";
}

function makeResultCode(moduleName, params) {
  return SchemaDrivenResultCode.make(moduleName, printType(params), printStruct(params));
}

exports.printStruct = printStruct;
exports.printType = printType;
exports.makeResultCode = makeResultCode;
/* No side effect */
