// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenResultCode = require("./SchemaDrivenResultCode.bs.js");
var SchemaDrivenNamesCorrector = require("./SchemaDrivenNamesCorrector.bs.js");

function prefixPlugin(prefix, resultCodeDeclar) {
  return SchemaDrivenResultCode.editModuleName(resultCodeDeclar, (function (n) {
                return SchemaDrivenNamesCorrector.modifyModuleName(prefix) + n;
              }));
}

function postfixPlugin(prefix, resultCodeDeclar) {
  return SchemaDrivenResultCode.editModuleName(resultCodeDeclar, (function (n) {
                return n + SchemaDrivenNamesCorrector.modifyModuleName(prefix);
              }));
}

exports.prefixPlugin = prefixPlugin;
exports.postfixPlugin = postfixPlugin;
/* No side effect */
