// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");
var SchemaDrivenResultCode = require("./SchemaDrivenResultCode.bs.js");

function printStruct(m) {
  return "S.null(" + SchemaDrivenModule.moduleName(m) + ".struct)";
}

function printType(m) {
  return "option<" + SchemaDrivenModule.moduleName(m) + ".t>";
}

function makeResultCode(moduleName, t) {
  return SchemaDrivenResultCode.make(moduleName, printType(t), printStruct(t));
}

exports.printStruct = printStruct;
exports.printType = printType;
exports.makeResultCode = makeResultCode;
/* No side effect */
