// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var SchemaDrivenModule = require("./SchemaDrivenModule.bs.js");
var SchemaDrivenResultCode = require("./SchemaDrivenResultCode.bs.js");

function printStruct(props, strict) {
  var propRows = Belt_Array.map(props, (function (p) {
          var propName = p._0;
          return "  " + propName + ": o->S.field(\"" + propName + "\", " + SchemaDrivenModule.moduleName(p._1) + ".struct)";
        }));
  var strictAnnot = strict ? "->S.Object.strict" : "->S.Object.strip";
  return "S.object(o => {\n" + propRows.join(",\n") + "\n})" + strictAnnot + "";
}

function printType(props) {
  var propRows = Belt_Array.map(props, (function (p) {
          return "  " + p._0 + ":  " + SchemaDrivenModule.moduleName(p._1) + ".t";
        }));
  return "{\n" + propRows.join(",\n") + "\n}";
}

function makeResultCode(moduleName, props, strict) {
  return SchemaDrivenResultCode.make(moduleName, printType(props), printStruct(props, strict));
}

exports.printStruct = printStruct;
exports.printType = printType;
exports.makeResultCode = makeResultCode;
/* No side effect */
